# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server.models.message import Message  # noqa: F401,E501
from swagger_server import util


class Messages(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, messages: List[Message]=None):  # noqa: E501
        """Messages - a model defined in Swagger

        :param messages: The messages of this Messages.  # noqa: E501
        :type messages: List[Message]
        """
        self.swagger_types = {
            'messages': List[Message]
        }

        self.attribute_map = {
            'messages': 'messages'
        }

        self._messages = messages

    @classmethod
    def from_dict(cls, dikt) -> 'Messages':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Messages of this Messages.  # noqa: E501
        :rtype: Messages
        """
        return util.deserialize_model(dikt, cls)

    @property
    def messages(self) -> List[Message]:
        """Gets the messages of this Messages.


        :return: The messages of this Messages.
        :rtype: List[Message]
        """
        return self._messages

    @messages.setter
    def messages(self, messages: List[Message]):
        """Sets the messages of this Messages.


        :param messages: The messages of this Messages.
        :type messages: List[Message]
        """

        self._messages = messages
