# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Rider(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, id: int=None, spot_key: str=None, name: str=None):  # noqa: E501
        """Rider - a model defined in Swagger

        :param id: The id of this Rider.  # noqa: E501
        :type id: int
        :param spot_key: The spot_key of this Rider.  # noqa: E501
        :type spot_key: str
        :param name: The name of this Rider.  # noqa: E501
        :type name: str
        """
        self.swagger_types = {
            'id': int,
            'spot_key': str,
            'name': str
        }

        self.attribute_map = {
            'id': 'id',
            'spot_key': 'spotKey',
            'name': 'name'
        }

        self._id = id
        self._spot_key = spot_key
        self._name = name

    @classmethod
    def from_dict(cls, dikt) -> 'Rider':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Rider of this Rider.  # noqa: E501
        :rtype: Rider
        """
        return util.deserialize_model(dikt, cls)

    @property
    def id(self) -> int:
        """Gets the id of this Rider.


        :return: The id of this Rider.
        :rtype: int
        """
        return self._id

    @id.setter
    def id(self, id: int):
        """Sets the id of this Rider.


        :param id: The id of this Rider.
        :type id: int
        """

        self._id = id

    @property
    def spot_key(self) -> str:
        """Gets the spot_key of this Rider.


        :return: The spot_key of this Rider.
        :rtype: str
        """
        return self._spot_key

    @spot_key.setter
    def spot_key(self, spot_key: str):
        """Sets the spot_key of this Rider.


        :param spot_key: The spot_key of this Rider.
        :type spot_key: str
        """
        if spot_key is None:
            raise ValueError("Invalid value for `spot_key`, must not be `None`")  # noqa: E501

        self._spot_key = spot_key

    @property
    def name(self) -> str:
        """Gets the name of this Rider.


        :return: The name of this Rider.
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name: str):
        """Sets the name of this Rider.


        :param name: The name of this Rider.
        :type name: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name
