---
swagger: "2.0"
info:
  description: "Rando Track Brevet SPOT Tracker \n[http://swagger.io](http://swagger.io)\
    \ or on \n[irc.freenode.net, #swagger](http://swagger.io/irc/).\n"
  version: "1.0.0"
  title: "RandoTrack"
  termsOfService: "http://swagger.io/terms/"
  contact:
    email: "apiteam@swagger.io"
  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
host: "virtserver.swaggerhub.com"
basePath: "/JHa13y/randotrack/1.0.0"
tags:
- name: "brevet"
  description: "Everything about your brevets"
  externalDocs:
    description: "Find out more"
    url: "http://swagger.io"
schemes:
- "https"
- "http"
paths:
  /riders/{riderID}:
    get:
      summary: "Find a rider by ID"
      description: "Returns a single rider"
      operationId: "get_rider_by_id"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "riderID"
        in: "path"
        description: "ID of rider to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Rider"
        400:
          description: "Invalid ID supplied"
        404:
          description: "event not found"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /riders/{riderID}/messages:
    get:
      summary: "Find last spot messages for rider"
      description: "Returns spot messages for a single rider"
      operationId: "get_rider_messages_by_id"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "riderID"
        in: "path"
        description: "ID of rider we are getting the events for"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Messages"
        400:
          description: "Invalid ID supplied"
        404:
          description: "event not found"
      x-swagger-router-controller: "swagger_server.controllers.default_controller"
  /event/{eventId}:
    get:
      tags:
      - "event"
      summary: "Find event by ID"
      description: "Returns a single event"
      operationId: "get_event_by_id"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "eventId"
        in: "path"
        description: "ID of eventId to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Event"
        400:
          description: "Invalid ID supplied"
        404:
          description: "event not found"
      x-swagger-router-controller: "swagger_server.controllers.event_controller"
    post:
      tags:
      - "event"
      summary: "Updates a event in the with form data"
      operationId: "update_event_with_form"
      consumes:
      - "application/x-www-form-urlencoded"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "eventId"
        in: "path"
        description: "ID of event that needs to be updated"
        required: true
        type: "integer"
        format: "int64"
      - name: "name"
        in: "formData"
        description: "Updated name of the event"
        required: false
        type: "string"
      - name: "status"
        in: "formData"
        description: "Updated status of the event"
        required: false
        type: "string"
      responses:
        405:
          description: "Invalid input"
      x-swagger-router-controller: "swagger_server.controllers.event_controller"
    delete:
      tags:
      - "event"
      summary: "Deletes a event"
      operationId: "delete_event"
      produces:
      - "application/json"
      - "application/xml"
      parameters:
      - name: "api_key"
        in: "header"
        required: false
        type: "string"
      - name: "eventId"
        in: "path"
        description: "event id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        400:
          description: "Invalid ID supplied"
        404:
          description: "event not found"
      x-swagger-router-controller: "swagger_server.controllers.event_controller"
definitions:
  Rider:
    type: "object"
    required:
    - "name"
    - "spotKey"
    properties:
      id:
        type: "integer"
        format: "int64"
      spotKey:
        type: "string"
      name:
        type: "string"
        example: "11601 Josh Haley"
    example:
      spotKey: "spotKey"
      name: "11601 Josh Haley"
      id: 0
  Messages:
    type: "object"
    properties:
      messages:
        xml:
          name: "messages"
          wrapped: true
    example:
      messages: ""
  Message:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      unixTime:
        type: "string"
      messageType:
        type: "string"
        example: "OK"
      lat:
        type: "number"
        format: "double"
      long:
        type: "number"
        format: "double"
      message:
        type: "string"
      dateTime:
        type: "string"
  Event:
    type: "object"
    required:
    - "name"
    - "rideWithGPSurl"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        example: "doggie"
      rideWithGPSurl:
        type: "string"
      tags:
        type: "array"
        xml:
          name: "riders"
          wrapped: true
        items:
          $ref: "#/definitions/Rider"
    xml:
      name: "Event"
    example:
      name: "doggie"
      id: 0
      rideWithGPSurl: "rideWithGPSurl"
      tags:
      - spotKey: "spotKey"
        name: "11601 Josh Haley"
        id: 0
      - spotKey: "spotKey"
        name: "11601 Josh Haley"
        id: 0
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"
